application: notsafeanymo
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css

- url: /data
  static_dir: data

- url: /lib
  static_dir: lib

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: .*
  script: index.html
